version: '2.1'
services:
  control:
    container_name: control
    hostname: control
    build: ./control
    privileged: true
    links:
      - master
      - n1
      - n2
      - n3
      - n4
      - n5
    volumes:
        - /home/ssmike/src/clj/yt-kv:/src
  master:
    container_name: jepsen-master
    build: ./master
    hostname: master
    privileged: true
  node:
      container_name: jepsen-node-prototype
      privileged: true
      build: ./node
  n1:
    extends: node
    container_name: jepsen-n1
    hostname: n1
  n2:
    extends: node
    container_name: jepsen-n2
    hostname: n2
  n3:
    extends: node
    container_name: jepsen-n3
    hostname: n3
  n4:
    extends: node
    container_name: jepsen-n4
    hostname: n4
  n5:
    extends: node
    container_name: jepsen-n5
    hostname: n5
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "2402:9400:1000:7::/64"
